// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public partial class Book : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The authorId property</summary>
        public int? AuthorId { get; set; }
        /// <summary>The bookId property</summary>
        public int? BookId { get; set; }
        /// <summary>The dewyClass property</summary>
        public int? DewyClass { get; set; }
        /// <summary>The isAvailable property</summary>
        public bool? IsAvailable { get; set; }
        /// <summary>The isbn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Isbn { get; set; }
#nullable restore
#else
        public string Isbn { get; set; }
#endif
        /// <summary>The isDeleted property</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The year property</summary>
        public int? Year { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.Book"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.Book CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.Book();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authorId", n => { AuthorId = n.GetIntValue(); } },
                { "bookId", n => { BookId = n.GetIntValue(); } },
                { "dewyClass", n => { DewyClass = n.GetIntValue(); } },
                { "isAvailable", n => { IsAvailable = n.GetBoolValue(); } },
                { "isDeleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "isbn", n => { Isbn = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "year", n => { Year = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("authorId", AuthorId);
            writer.WriteIntValue("bookId", BookId);
            writer.WriteIntValue("dewyClass", DewyClass);
            writer.WriteBoolValue("isAvailable", IsAvailable);
            writer.WriteStringValue("isbn", Isbn);
            writer.WriteBoolValue("isDeleted", IsDeleted);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("year", Year);
        }
    }
}
#pragma warning restore CS0618
